run:
  timeout: 5m

linters-settings:
  govet:
    enable:
      - shadow
  gofumpt:
    extra-rules: true

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt

issues:
  exclude-use-default: false
