package models

// ExecutionPlan represents a strictly versioned execution plan generated by the Planner
type ExecutionPlan struct {
	Version string     `yaml:"version" json:"version"`
	Tasks   []PlanTask `yaml:"tasks" json:"tasks"`
}

// PlanTask represents a single unit of work in the ExecutionPlan
type PlanTask struct {
	ID        string   `yaml:"id" json:"id"`
	Plugin    string   `yaml:"plugin" json:"plugin"`
	DependsOn []string `yaml:"depends_on,omitempty" json:"depends_on,omitempty"`
}
